# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4f465a1a7a230bbea5bbfbe6564e52a0"
name = "alena-test-app-2"
application_url = "https://johnny-olympus-magnet-joke.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "gwa-study-alena-checkout.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_cart_transforms,write_delivery_customizations,write_products"

[auth]
redirect_urls = [
  "https://johnny-olympus-magnet-joke.trycloudflare.com/auth/callback",
  "https://johnny-olympus-magnet-joke.trycloudflare.com/auth/shopify/callback",
  "https://johnny-olympus-magnet-joke.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
